/*VERIFICAR LA INFORMACION DEL PROCESO REALIZADO A TRAVÉS DE UNA CONSULTA

CMD / ACCEDEMOS A MYSQL POR MEDIO DEL BIN (C:/MYSQL/MYSQLSERVERX.X/BIN) / mysql -uroot -p / 
USE <NOMBRE_DB>;
EXPLAIN <QUERY-A_INSPECCIONAR>;
EXPLAIN <QUERY_A_INSPECCIONAR> \G;
EXPLAIN FORMAT=JSON <QUERY_A_INSPECCIONAR> \G;

DENTRO DEL JSON NOS INDICA EL QUERY_COST QUE INDICA EL COSTO DE LOS RECURSOS USADOS PARA LA QUERY

ENTRE MÁS JOINS MAYOR COSTO DE RECURSO
*/

-- QUERY_COST: 3.75
SELECT A.CODIGO_DEL_PRODUCTO FROM TABLA_DE_PRODUCTOS A;

-- QUERY_COST: 138660.92
SELECT A.CODIGO_DEL_PRODUCTO,YEAR(B.FECHA_VENTA), SUM(C.CANTIDAD) FROM TABLA_DE_PRODUCTOS A
INNER JOIN ITEMS_FACTURAS C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN FACTURAS B
ON C.NUMERO = B.NUMERO
GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(B.FECHA_VENTA)
ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(B.FECHA_VENTA);

/*INDICES
ALGORITMO BTREE
	- ARBOL BINARIO: 
		+ VALORES A LA IZQ DEL NODO SON MENORES
        + VALORES A LA DERECHA SON MAYORES
	- CONSIDERACIONES BTREE
		+ BALANCED BINARY TREE
        + MÁS 4 BILLONES DE REGISTROS EN 32 NIVELES
        
HASH
	- MAPEA DATOS GRANDES DE TAMAÑOS VARIABLES EN UN TAMAÑO FIJO
    - CUANDO ABIRMOS UN LIBRO, BUSCAMOS EL INDICE PARA ENCONTRAR LA PAGINA QUE DESEAMOS CONSULTAR
    - CRIPTOGRAFIA, ALMACENA CONTRASEÑAS, ENTRE OTROS
*/

-- COST "8850.35"
EXPLAIN FORMAT=JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA = '20170101';

/*CREANDO INDICES
ALTER TABLE <NOMBRE_TB> ADD INDEX (CAMPO_INDEX);

ALTER TABLE FACTURAS ADD INDEX(FECHA_VENTA);

BORRAR INDEX
ALTER TABLE <NOMBRE_TB> DROP INDEX <CAMPO_INDEX>;
*/

-- COST "25.90"
EXPLAIN FORMAT=JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA = '20170101'; -- CON INDEX (FECHA_VENTA);

/*MYSQL LAB
ACCEDEMOS AL BIN DE MYSQL A TRAVÉS DE CMD
mysqlslap -uroot -p --concurrency=100 --iterations=10 --create-schema=jugos_ventas --query: "<QUERY>";


SELECT * FROM FACTURAS WHERE FECHA_VENTA = "20170101";

ALTER TABLE FACTURAS ADD INDEX(FECHA_VENTA);*/

ALTER TABLE FACTURAS DROP INDEX FECHA_VENTA;

ALTER TABLE facturas ADD INDEX(FECHA_VENTA);

/*CREANDO USUARIO ADMIN
ADMINISTRATION / USERS AND PRIVILAGES

creando usuarios
CREATE USER '<NOMBRE_USUARIO>'@'localhost' INDENTIED BY 'admin02';

dar permisos
GRANT  ALL PREVILEGES ON *.* TO '<NOMBRE_USUARIO>'@'LOCALHOST' WITH GRANT OPTION;

creando usuario comunes
CREATE USER '<NOMBRE_USUARIO>'@'localhost' INDENTIED BY 'admin02';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE 
ON *.* TO '<NOMBRE_USUARIO>'@'LOCALHOST' WITH GRANT OPTION;

creando usuario de solo lectura
CREATE USER '<NOMBRE_USUARIO>'@'localhost' INDENTIFY BY 'read01';

GRANT SELECT, EXECUTE ON *.* TO '<NOMBRE_USUARIO>@'localhost';	 

creando usuario para back-up
CREATE USER '<NOMBRE_USUARIO>'@'localhost' INDENTIFY BY 'backup01';

GRANT SELECT, RELOAD, LOCK TABLES, REPLICATION CLIENT ON *.* TO '<NOMBRE_USUARIO>@'localhost';	 
*/

/*ACCEDIENDO A CUALQUIER SERVIDOR
CREATE USER '<NOMBRE_USUARIO>'@'%' INDENTIFY BY 'ADMIN_G';

GRANT SELECT, RELOAD, LOCK TABLES, REPLICATION CLIENT ON *.* TO '<NOMBRE_USUARIO>@'%';	 

USANDO %

- 192.168.1.% => 192.168.1.0 - 192.168.1.255
- 192.168.1.1_ => 192.168.1.100 - 192.168.1.255
- client_.mycompany.com => clientXY.mycompany.com

*/

/*LIMITANDO ACCESO A TABLAS

ADMINISTRATION / USER AND PRIVILEGES / SCHEMA PRIVILEGES

comandos
CREATE USER '<NOMBRE_USUARIO>'@'%' INDENTIFY BY 'USER';

GRANT SELECT, UPDATE, INSERT, EXECUTE, DELETE, LOCK TABLES, CREATE TEMPORARY TABLE 
ON <NOMBRE_DB>.* TO '<NOMBRE_USUARIO>@'%';	 


CREATE USER '<NOMBRE_USUARIO>'@'%' INDENTIFY BY 'USER01';

GRANT SELECT, UPDATE, INSERT, DELETE      
ON <NOMBRE_DB>.<NOMBRE_TABLA> TO '<USER01>@'%';	 

puedes otorgar diferentes permisos para cada tabla por usuario
GRANT SELECT ON <NOMBRE_DB>.<NOMBRE_TABLA> TO '<USER01>@'%';	 


REVOCANDO PRIVILEGIOS

primero revisamos los privilegios actuales de todos los usuarios
SELECT * FROM mysql.user;


SHOW GRANTS FOR '<user>'@'localhost';

REVOKE ALL PRIVILEGES, GRANT OPTION FROM '<USER>'@<localhost>';

*/

SELECT * FROM mysql.user;

SHOW GRANTS FOR 'admin'@'localhost';